import Head from 'next/head'
import Router from 'next/router'

/* Components */
import MainContainer from '@/components/MainContainer'

export default function Home() {
    return (
        <>
            <Head>
                <title>JOJO&apos;S RPG</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainContainer>
                <button onClick={() => Router.push('/login')}>LOGIN</button>
                <button onClick={() => Router.push('/register')}>REGISTRAR</button>
            </MainContainer>
        </>
    )
}
